import type { Metadata } from 'next'
import Image from 'next/image'
import SectionLabel from '@/components/ui/SectionLabel'
import ScrollReveal from '@/components/ui/ScrollReveal'
import Button from '@/components/ui/Button'
import HoverCard from '@/components/ui/HoverCard'

export const metadata: Metadata = {
  title: 'Tachyon AI — Business Automation Systems | HypeHouse Digital',
  description:
    'Tachyon is HypeHouse Digital\'s AI automation division. We design, build, and operate the business systems that remove friction, eliminate manual work, and create compounding growth.',
  alternates: { canonical: 'https://hypehouse.digital/tachyon' },
}

const services = [
  {
    icon: '⚡',
    title: 'Instant Response',
    description: 'Smart, on-brand emails sent automatically the moment someone shows interest. No delays. No missed leads.',
  },
  {
    icon: '📅',
    title: 'Smart Booking',
    description: 'Campaigns connect to an intelligent calendar system. Clients book calls instantly with zero back-and-forth.',
  },
  {
    icon: '◈',
    title: 'CRM Sync',
    description: 'Your CRM updates automatically. Contacts created, status logged, tasks assigned — no human input needed.',
  },
  {
    icon: '◉',
    title: 'AI Outreach',
    description: 'Hyper-personalised emails generated by AI, sent from your real email to any lead list.',
  },
  {
    icon: '💬',
    title: 'WhatsApp Automation',
    description: 'Broadcast campaigns, automated responses, lead qualification flows — all inside WhatsApp.',
  },
  {
    icon: '◆',
    title: 'Reporting Dashboards',
    description: 'Live dashboards that show you exactly what is working, updated in real time.',
  },
]

const impacts = [
  'Stop losing warm leads',
  'Respond before competitors',
  'Book qualified calls automatically',
  'Clean, smart CRM — always updated',
  'Your team focuses on closing, not admin',
  'Invisible automation — clients never know it\'s there',
]

export default function TachyonPage() {
  return (
    <>
      {/* ── HERO ─────────────────────────────────────────────────────────── */}
      <section style={{
        position: 'relative', zIndex: 10,
        padding: '160px 48px 120px', textAlign: 'center', overflow: 'hidden',
      }}>
        {/* Blue plasma background */}
        <div style={{
          position: 'absolute', inset: '-50%',
          background: 'conic-gradient(from 0deg, transparent 0deg, rgba(4,157,255,0.12) 60deg, rgba(12,18,141,0.08) 120deg, transparent 180deg, rgba(4,157,255,0.06) 240deg, transparent 360deg)',
          animation: 'plasma-rotate 25s linear infinite',
          pointerEvents: 'none',
        }} />
        <div style={{
          position: 'absolute', inset: 0,
          background: 'radial-gradient(ellipse 80% 70% at 50% 40%, rgba(4,157,255,0.10) 0%, transparent 65%)',
          pointerEvents: 'none',
        }} />

        <div style={{ maxWidth: '900px', margin: '0 auto', position: 'relative' }}>
          {/* Tachyon wordmark */}
          <div style={{
            fontFamily: 'var(--font-poppins)', fontWeight: 800,
            fontSize: 'clamp(48px, 10vw, 120px)', letterSpacing: '-0.03em',
            lineHeight: 1, marginBottom: '12px',
            background: 'linear-gradient(135deg, #049DFF 0%, #0C128D 60%, #049DFF 100%)',
            backgroundSize: '200% 200%',
            WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
            backgroundClip: 'text', animation: 'gradient-shift 4s ease infinite',
          }}>
            TACHYON
          </div>
          <div style={{
            fontFamily: 'var(--font-poppins)', fontWeight: 500, fontSize: '13px',
            letterSpacing: '0.2em', textTransform: 'uppercase' as const,
            color: 'rgba(4,157,255,0.7)', marginBottom: '40px',
          }}>
            A HypeHouse Sub-Brand · Automation &amp; AI Intelligence
          </div>

          <h1 style={{
            fontFamily: 'var(--font-poppins)', fontWeight: 800,
            fontSize: 'clamp(32px, 5vw, 68px)', color: 'white',
            letterSpacing: '-0.02em', lineHeight: 1.1, marginBottom: '16px',
          }}>
            Business Systems That Think For You.
          </h1>
          <h2 style={{
            fontFamily: 'var(--font-poppins)', fontWeight: 600,
            fontSize: 'clamp(20px, 3vw, 36px)', marginBottom: '28px',
            color: '#049DFF',
          }}>
            We build it. We run it. You grow.
          </h2>
          <p style={{
            fontSize: '18px', color: 'rgba(255,255,255,0.80)',
            lineHeight: 1.75, maxWidth: '620px', margin: '0 auto 48px',
          }}>
            Tachyon is the automation and AI intelligence division of HypeHouse. We design, build, and operate the business systems that remove friction, eliminate manual work, and create compounding growth.
          </p>
          <Button href="https://hypehouse-client-intake-form.netlify.app" variant="primary" external>
            Get a Custom Quote →
          </Button>
        </div>
      </section>

      {/* ── ADDITIONAL IMAGE ─────────────────────────────────────────────── */}
      <section style={{ position: 'relative', zIndex: 10, padding: '0 48px 80px' }}>
        <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
          <ScrollReveal>
            <div style={{ position: 'relative', width: '100%', minHeight: '420px', borderRadius: '12px', overflow: 'hidden', border: '1px solid rgba(4,157,255,0.25)' }}>
              <Image src="/images/additional-2.png" alt="Tachyon AI System" fill style={{ objectFit: 'cover', objectPosition: 'center' }} />
            </div>
          </ScrollReveal>
        </div>
      </section>

      {/* ── THE PROBLEM ──────────────────────────────────────────────────── */}
      <section style={{
        position: 'relative', zIndex: 10, padding: '100px 48px',
        background: 'rgba(4,157,255,0.03)',
        borderTop: '1px solid rgba(4,157,255,0.12)',
        borderBottom: '1px solid rgba(4,157,255,0.12)',
      }}>
        <div style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center' }}>
          <ScrollReveal>
            <SectionLabel>The Problem</SectionLabel>
            <h2 style={{
              fontFamily: 'var(--font-poppins)', fontWeight: 800,
              fontSize: 'clamp(28px, 4vw, 52px)', color: 'white',
              marginTop: '20px', marginBottom: '28px', letterSpacing: '-0.02em',
            }}>
              The Revenue Leak
            </h2>
            <p style={{ fontSize: '18px', color: 'rgba(255,255,255,0.80)', lineHeight: 1.75, marginBottom: '28px' }}>
              Your marketing is working. Traffic is coming. Clicks are happening. But leads go cold, CRMs stay outdated, follow-ups are missed.
            </p>
            <p style={{
              fontSize: 'clamp(20px, 3vw, 28px)',
              fontFamily: 'var(--font-poppins)', fontWeight: 700,
              color: '#049DFF', lineHeight: 1.4,
            }}>
              You&apos;re bleeding revenue at the back of the funnel.
            </p>
          </ScrollReveal>
        </div>
      </section>

      {/* ── WHAT TACHYON BUILDS ───────────────────────────────────────────── */}
      <section style={{ position: 'relative', zIndex: 10, padding: '120px 48px' }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
          <ScrollReveal>
            <div style={{ textAlign: 'center', marginBottom: '56px' }}>
              <SectionLabel>What Tachyon Builds</SectionLabel>
              <h2 style={{
                fontFamily: 'var(--font-poppins)', fontWeight: 800,
                fontSize: 'clamp(28px, 4vw, 52px)', color: 'white',
                marginTop: '20px', letterSpacing: '-0.02em',
              }}>
                Six systems.{' '}
                <span style={{
                  background: 'linear-gradient(135deg, #049DFF, #0C128D)',
                  WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text',
                }}>
                  Infinite leverage.
                </span>
              </h2>
            </div>
          </ScrollReveal>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px' }}>
            {services.map((item, i) => (
              <ScrollReveal key={item.title} delay={i * 80}>
                <HoverCard
                  style={{ padding: '40px 32px', height: '100%' }}
                  hoverStyle={{ borderColor: 'rgba(4,157,255,0.35)' }}
                  baseStyle={{ borderColor: 'rgba(4,157,255,0.12)' }}
                >
                  <div style={{ fontSize: '28px', color: '#049DFF', marginBottom: '16px' }}>{item.icon}</div>
                  <h3 style={{
                    fontFamily: 'var(--font-poppins)', fontWeight: 700,
                    fontSize: '20px', color: 'white', marginBottom: '12px',
                  }}>
                    {item.title}
                  </h3>
                  <p style={{ fontSize: '15px', color: 'rgba(255,255,255,0.75)', lineHeight: 1.7 }}>
                    {item.description}
                  </p>
                </HoverCard>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* ── BUSINESS IMPACT ───────────────────────────────────────────────── */}
      <section style={{
        position: 'relative', zIndex: 10, padding: '100px 48px',
        background: 'rgba(12,18,141,0.06)',
        borderTop: '1px solid rgba(4,157,255,0.10)',
        borderBottom: '1px solid rgba(4,157,255,0.10)',
      }}>
        <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
          <ScrollReveal>
            <div style={{ textAlign: 'center', marginBottom: '48px' }}>
              <SectionLabel>Business Impact</SectionLabel>
              <h2 style={{
                fontFamily: 'var(--font-poppins)', fontWeight: 800,
                fontSize: 'clamp(28px, 4vw, 48px)', color: 'white',
                marginTop: '20px', letterSpacing: '-0.02em',
              }}>
                What changes when Tachyon is running.
              </h2>
            </div>
          </ScrollReveal>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
            {impacts.map((item, i) => (
              <ScrollReveal key={item} delay={i * 60}>
                <div style={{
                  display: 'flex', alignItems: 'center', gap: '14px',
                  padding: '20px 24px',
                  background: 'rgba(4,157,255,0.05)',
                  border: '1px solid rgba(4,157,255,0.15)',
                  borderRadius: '10px',
                }}>
                  <span style={{ color: '#049DFF', fontSize: '16px', flexShrink: 0 }}>✦</span>
                  <span style={{ fontFamily: 'var(--font-poppins)', fontWeight: 500, fontSize: '16px', color: 'rgba(255,255,255,0.88)' }}>
                    {item}
                  </span>
                </div>
              </ScrollReveal>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING / CTA ─────────────────────────────────────────────────── */}
      <section style={{ position: 'relative', zIndex: 10, padding: '120px 48px 160px', textAlign: 'center' }}>
        <ScrollReveal>
          <div style={{
            maxWidth: '700px', margin: '0 auto',
            background: 'rgba(4,157,255,0.06)',
            border: '1px solid rgba(4,157,255,0.30)',
            borderRadius: '20px', padding: '64px 48px',
            position: 'relative', overflow: 'hidden',
          }}>
            <div style={{
              position: 'absolute', inset: '-50%',
              background: 'conic-gradient(from 0deg, transparent, rgba(4,157,255,0.05), transparent)',
              animation: 'plasma-rotate 20s linear infinite',
              pointerEvents: 'none',
            }} />
            <div style={{ position: 'relative' }}>
              <SectionLabel>Custom Quote</SectionLabel>
              <h2 style={{
                fontFamily: 'var(--font-poppins)', fontWeight: 800,
                fontSize: 'clamp(24px, 4vw, 44px)', color: 'white',
                marginTop: '20px', marginBottom: '16px', letterSpacing: '-0.02em',
              }}>
                Every Tachyon system is custom built.
              </h2>
              <p style={{
                fontSize: '17px', color: 'rgba(255,255,255,0.80)',
                lineHeight: 1.75, marginBottom: '12px', maxWidth: '500px', margin: '0 auto 12px',
              }}>
                We don&apos;t sell packages. We audit your business, identify where revenue is leaking, and build exactly the system you need.
              </p>
              <p style={{
                fontSize: '14px', color: 'rgba(4,157,255,0.8)',
                fontFamily: 'var(--font-poppins)', fontWeight: 500,
                letterSpacing: '0.05em', marginBottom: '36px',
              }}>
                Consult with us for your automation requirements.
              </p>
              <p style={{
                fontSize: '13px', color: 'rgba(255,255,255,0.45)',
                marginBottom: '36px', fontFamily: 'var(--font-poppins)',
              }}>
                Custom quote · Fully scoped · Built for your business
              </p>
              <Button href="https://hypehouse-client-intake-form.netlify.app" variant="primary" external>
                Book a Systems Consultation →
              </Button>
            </div>
          </div>
        </ScrollReveal>
      </section>
    </>
  )
}
